- name: Steam
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ 2E4C1A7613D8BEF1019F9BB071119421 }}
          plugin_steam: yes
          plugin_steam_user: "76561199120105703"
          plugin_steam_sections: recently-played



